import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useQuery } from "@tanstack/react-query";

interface fetchSomething {
  id: number;
  body: string;
}

const fetchSomething = async () => {
  const response = await axios.get(
    `https://api.github.com/repos/uidotdev/usehooks/issues?state=closed`
  );
  const data: fetchSomething[] = response.data;
  return data;
};

export default function Home() {
  const { data, isLoading, isError } = useQuery(["issues"], fetchSomething);
  if (isLoading) {
    return <p>LOADING...</p>;
  }

  if (!data || isError) {
    return <p>Something went wrong</p>;
  }
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Closed Issues</h1>
        <ul>
          {data.map((issue) => (
            <li key={issue.id}>{issue.body}</li>
          ))}
        </ul>
      </main>
    </>
  );
}
